-- Olist E-commerce Project

/* Loading data into SQL from python.8
*/
Use [Olist Ecommerce];


-- CHANGING THE NAMES OF TABLES.
EXEC sp_rename 'olist_SELLER', 'OLIST_SELLER';
EXEC sp_rename 'OLIST_NAME_TRANSLATION' ,'OLIST_PROD_CATEG_TRANSLATION';



-- VALIDATING COLUMNS FOR CONSTRIANTS


-- OLIST_CUSTOMER.
--changing the data type from varchar(max) to varchar(35).

Alter table olist_CUSTOMER
alter column CUSTOMER_ID varchar(35) not null;

ALTER TABLE olist_customer
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID);


-- OLIST_ORDER.

Alter table olist_ORDER
alter column ORDER_ID varchar(35) not null;

ALTER TABLE OLIST_ORDER
ALTER COLUMN CUSTOMER_ID VARCHAR(35);

ALTER TABLE OLIST_ORDER 
ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID);

ALTER TABLE OLIST_ORDER
ADD CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES OLIST_CUSTOMER(CUSTOMER_ID);


-- OLIST_GEOLOCATION.

-- REMOVING DUPLICATES
CREATE TABLE OLIST_LOCATION (
ZIP_CODE VARCHAR(10) PRIMARY KEY,
LATITUDE FLOAT NOT NULL,
LONGITUDE FLOAT NOT NULL,
CITY VARCHAR(100),
STATE VARCHAR(10)
);


INSERT INTO OLIST_LOCATION(ZIP_CODE, LATITUDE,LONGITUDE,CITY, STATE)
SELECT DISTINCT GEOLOCATION_ZIP_CODE_PREFIX,
	MIN(GEOLOCATION_LAT),
	MIN(GEOLOCATION_LNG),
	MIN(GEOLOCATION_CITY),
	MIN(GEOLOCATION_STATE) 
FROM OLIST_GEOLOCATION
GROUP BY GEOLOCATION_ZIP_CODE_PREFIX;


-- DELETING THE OLD TABLE

DROP TABLE OLIST_GEOLOCATION;

-- ADDING ZIP_CODE AS FK INTO CUSTOMER AND SELLER TABLE.
ALTER TABLE OLIST_CUSTOMER
ALTER COLUMN CUSTOMER_ZIP_CODE_PREFIX VARCHAR(10);

-- VALIDATING DATA FOR FOREIGN KEY CONSTRAINT

UPDATE C SET CUSTOMER_ZIP_CODE_PREFIX = 1001 FROM OLIST_CUSTOMER C WHERE NOT EXISTS ( 
SELECT 1 FROM OLIST_LOCATION L WHERE L.ZIP_CODE = C.CUSTOMER_ZIP_CODE_PREFIX);

-- ADDING FOREIGN KEY CONSTRAINT
ALTER TABLE OLIST_CUSTOMER
ADD CONSTRAINT FK_LOCATION_ZIP_CODE_CUSTOMER FOREIGN KEY (CUSTOMER_ZIP_CODE_PREFIX) REFERENCES OLIST_LOCATION(ZIP_CODE);


--CHANGING DATA TYPE OF SELLER_ZIP_CODE_PREFIX

ALTER TABLE OLIST_SELLER
ALTER COLUMN SELLER_ZIP_CODE_PREFIX VARCHAR(10);

-- ADDING CONSTRAINT

-- NORMALIZING ROWS THAT CAUSE FOREIGN KEY CONSTRAINT ISSUE
UPDATE S SET SELLER_ZIP_CODE_PREFIX = 1001 FROM OLIST_SELLER S WHERE NOT EXISTS (
SELECT 1 FROM OLIST_LOCATION L WHERE S.seller_zip_code_prefix = L.ZIP_CODE);

-- ADDING FK CONSTRAINT

ALTER TABLE OLIST_SELLER
ADD CONSTRAINT FK_LOCATION_ZIP_CODE_SELLER_LOC_ZIP_CODE FOREIGN KEY (SELLER_ZIP_CODE_PREFIX) REFERENCES OLIST_LOCATION(ZIP_CODE);



-- OLIST ORDER ITEM

ALTER TABLE OLIST_ORDER_ITEM
ALTER COLUMN ORDER_ID VARCHAR(100) NOT NULL;
ALTER TABLE OLIST_ORDER_ITEM
ALTER COLUMN ORDER_ITEM_ID VARCHAR(10) NOT NULL;

-- ADDING PRIMARY KEY CONSTRAINT

ALTER TABLE OLIST_ORDER_ITEM
ADD CONSTRAINT PK_ORDER_ID_ORDER_ITEM_ID PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID);

-- ADDING FK

ALTER TABLE OLIST_ORDER_ITEM
ALTER COLUMN PRODUCT_ID VARCHAR(100);

ALTER TABLE OLIST_ORDER_ITEM
ADD CONSTRAINT FK_PRODUCT_ID_OLIST_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES OLIST_PRODUCT(PRODUCT_ID) ;



--OLIST PRODUCT

SELECT * FROM OLIST_PRODUCT

-- ADDING PRIMARY KEY CONSRAINT

ALTER TABLE OLIST_PRODUCT
ALTER COLUMN PRODUCT_ID VARCHAR(100) NOT NULL;


ALTER TABLE OLIST_PRODUCT
ADD CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (PRODUCT_ID);

-- ADDING A FK CATEGORY_ID INTO OLIST PRODUCT TABLE FROM OLIST_PROD_CATEG_TRANSLATION

ALTER TABLE OLIST_PRODUCT
ADD CATEGORY_ID INT NULL;


UPDATE P
SET P.CATEGORY_ID = T.CATEGORY_ID
FROM OLIST_PRODUCT P JOIN OLIST_PROD_CATEG_TRANSLATION T ON P.product_category_name = T.PRODUCT_CATEGORY_NAME;

ALTER TABLE OLIST_PRODUCT
ADD CONSTRAINT FK_CATEGORY_ID_PROD_CATEG FOREIGN KEY(CATEGORY_ID) REFERENCES OLIST_PROD_CATEG_TRANSLATION(CATEGORY_ID);



-- OLIST ORDER PAYMENT
ALTER TABLE OLIST_ORDER_PAYMENT 
ALTER COLUMN ORDER_ID VARCHAR(35) NOT NULL;

ALTER TABLE OLIST_ORDER_PAYMENT
ALTER COLUMN PAYMENT_SEQUENTIAL INT NOT NULL;

-- ADDING PK CONSTRAINT
ALTER TABLE OLIST_ORDER_PAYMENT
ADD CONSTRAINT PK_ORDER_ID_PAYMENT_SEQUENTIAL PRIMARY KEY (ORDER_ID, PAYMENT_SEQUENTIAL);

-- ADDING FOREIGN KEY

ALTER TABLE OLIST_ORDER_PAYMENT
ADD CONSTRAINT FK_ORDER_ID FOREIGN KEY(ORDER_ID) REFERENCES OLIST_ORDER(ORDER_ID);



-- ORDER REVIEW

SELECT * FROM OLIST_ORDER_REVIEW

ALTER TABLE OLIST_ORDER_REVIEW
ALTER COLUMN REVIEW_ID VARCHAR(100) NOT NULL;

ALTER TABLE OLIST_ORDER_REVIEW
ALTER COLUMN ORDER_ID VARCHAR(35) NOT NULL;


--ADDING CONSTRAINTS (PK AND FK)

ALTER TABLE OLIST_ORDER_REVIEW
ADD CONSTRAINT PK_ORDER_ID_REVIEW_ID PRIMARY KEY (REVIEW_ID, ORDER_ID);

ALTER TABLE OLIST_ORDER_REVIEW
ADD CONSTRAINT FK_ORDER_ID_REVIEW FOREIGN KEY (ORDER_ID) REFERENCES OLIST_ORDER(ORDER_ID);



-- OLIST PROD CATEG TRANSLATION

-- ADDING PRIMARY KEY
ALTER TABLE OLIST_PROD_CATEG_TRANSLATION
ADD CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY;



-- OLIST_SELLER

-- ADDING PRIMARY KEY
ALTER TABLE OLIST_SELLER
ALTER COLUMN SELLER_ID VARCHAR(100) NOT NULL;
ALTER TABLE OLIST_SELLER
ADD CONSTRAINT PK_SELLER_ID PRIMARY KEY (SELLER_ID);

-- REMOVING REDUNDANT COLUMN DATA FROM CUSTOMER AND SELLER TABLE

ALTER TABLE OLIST_CUSTOMER
DROP COLUMN CUSTOMER_CITY, CUSTOMER_STATE;

ALTER TABLE OLIST_SELLER
DROP COLUMN SELLER_CITY, SELLER_STATE;